module.exports.categoryImages = {
  wedding: [
    'portfolio/wedding/(1)',
    'portfolio/wedding/(2)',
    'portfolio/wedding/(3)',
    'portfolio/wedding/(4)',
    'portfolio/wedding/(5)',
    'portfolio/wedding/(6)',
    'portfolio/wedding/(7)',
    'portfolio/wedding/(8)',
    'portfolio/wedding/(9)',
    'portfolio/wedding/(19)',    
    'portfolio/wedding/(10)',
    'portfolio/wedding/(11)',
    'portfolio/wedding/(16)',
    'portfolio/wedding/(12)',
    'portfolio/wedding/(13)',
    'portfolio/wedding/(14)',
    'portfolio/wedding/(15)',
    'portfolio/wedding/(17)',
    'portfolio/wedding/(18)',
  ],
  portrait: [
    'portfolio/portrait/(1)',
    'portfolio/portrait/(2)',
    'portfolio/portrait/(3)',
    'portfolio/portrait/(4)',
    'portfolio/portrait/(5)',
    'portfolio/portrait/(6)',
    'portfolio/portrait/(7)',
    'portfolio/portrait/(8)',
    'portfolio/portrait/(9)',
    'portfolio/portrait/(10)',
    'portfolio/portrait/(11)',
    'portfolio/portrait/(12)',
    'portfolio/portrait/(13)',
    'portfolio/portrait/(20)',
    'portfolio/portrait/(14)',
    'portfolio/portrait/(15)',
    'portfolio/portrait/(16)',
    'portfolio/portrait/(17)',
    'portfolio/portrait/(18)',
    'portfolio/portrait/(19)',
    'portfolio/portrait/(21)',
    'portfolio/portrait/(22)',
    'portfolio/portrait/(23)',
    'portfolio/portrait/(24)',
    'portfolio/portrait/(25)',
    'portfolio/portrait/(26)',
    'portfolio/portrait/(27)',
  ],
  haldi: [
    'portfolio/haldi/(1)',
    'portfolio/haldi/(2)',
    'portfolio/haldi/(3)',
    'portfolio/haldi/(4)',
    'portfolio/haldi/(5)',
    'portfolio/haldi/(6)',
    'portfolio/haldi/(7)',
    'portfolio/haldi/(8)',
    'portfolio/haldi/(9)',
    'portfolio/haldi/(10)',
    'portfolio/haldi/(11)',
    'portfolio/haldi/(12)',
    'portfolio/haldi/(13)',
    'portfolio/haldi/(14)',
    'portfolio/haldi/(15)',
    'portfolio/haldi/(16)',
    'portfolio/haldi/(17)',
    'portfolio/haldi/(18)',
    'portfolio/haldi/(19)',
  ],
  prewedding: [
    'portfolio/prewedding/(1)',
    'portfolio/prewedding/(2)',
    'portfolio/prewedding/(3)',
    'portfolio/prewedding/(4)',
    'portfolio/prewedding/(5)',
    'portfolio/prewedding/(6)',
    'portfolio/prewedding/(7)',
    'portfolio/prewedding/(8)',
    'portfolio/prewedding/(9)',
    'portfolio/prewedding/(10)',
    'portfolio/prewedding/(11)',
    'portfolio/prewedding/(12)',
    'portfolio/prewedding/(13)',
    'portfolio/prewedding/(14)',
  ],
  mehndi: [
    'portfolio/mehndi/(1)',
    'portfolio/mehndi/(2)',
    'portfolio/mehndi/(3)',
    'portfolio/mehndi/(4)',
  ],
  // birthday: [
  //   '/images/event1',
  //   '/images/event2',
  // ],
};